version: '3.7'
services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://todoapp@postgres/todos
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'team_manager'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'