version: '3.7'
services:
  app:
    image: tjohnson/team-manager-server
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    # environment:
    #   - DATABASE_URL=mysql://todoapp@postgres/todos
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=web
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=team_manager
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql-data: