version: '3.7'
services:
  server:
    container_name: server
    image: tjohnson/team-manager-server
    env_file: .env
    environment:
      - DB_HOST=mysql
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    ports:
      - '3000:3000'
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=team_manager
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql-data: