name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag team-manager-server:$(date +%s)
    - name: Run unit tests in Docker
      run: docker run --rm --entrypoint=npm team-manager-server:$(date +%s) test
